# Generated by Django 4.0.3 on 2022-03-30 19:18

import django.core.validators
from django.db import migrations, models

import utils.avatar_util


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.avatar_util.AvatarUtils.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number ex. +380xxxxxxxxx')]),
        ),
    ]
