# Generated by Django 4.0.3 on 2022-04-05 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_profilemodel_avatar_alter_profilemodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?=.{3,32}$)[a-zA-Z0-9]+(?<![_.])$', 'Name must contain only letters and must contain 4 to 32 characters')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?=.{3,32}$)[a-zA-Z0-9]+(?<![_.])$', 'Surname must contain only letters and must contain 4 to 32 characters')]),
        ),
    ]
