# Generated by Django 4.0.3 on 2022-04-08 18:14

import django.core.validators
from django.db import migrations, models
import utils.avatar_util


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=utils.avatar_util.AvatarUtils.upload_to),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?=.{3,32}$)[a-zA-Z0-9]+(?<![_.])$', 'Name must contain only letters and must contain 4 to 32 characters')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number ex. +380xxxxxxxxx')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='surname',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^(?=.{3,32}$)[a-zA-Z0-9]+(?<![_.])$', 'Surname must contain only letters and must contain 4 to 32 characters')]),
        ),
    ]
