# Generated by Django 4.0.3 on 2022-04-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carmodel_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ('id',), 'verbose_name': 'Car'},
        ),
    ]
